version: '3.6'

networks:
  api-network:

services:
  api:
    build: .
    ports:
      - $PORT:$PORT
    networks:
      - api-network
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=$PORT
