version: '3'

networks:
  api_network:

services:
  api:
    build:
      context: .
      args:
        - PORT=$PORT
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
    networks:
      - api_network
    ports:
      - $PORT:$PORT
    restart: always

  postgres:
    image: clkao/postgres-plv8:12-2
    ports:
      - 5432:5432
    networks:
      - api_network
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
