version: '3'

networks:
  api_network:

services:
  api:
    build: .
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
      - DB_HOST=postgres
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
    networks:
      - api_network
    ports:
      - $PORT:$PORT
    restart: always
    volumes:
      - ./storage:/usr/src/app/storage
  postgres:
    image: clkao/postgres-plv8:12-2
    networks:
      - api_network
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    restart: always
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
