version: '3'

networks:
  api_network:

services:
  api:
    build:
      context: .
      args:
        - PORT=$PORT
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_POOL_MIN=$POSTGRES_POOL_MIN
      - POSTGRES_POOL_MAX=$POSTGRES_POOL_MAX
    networks:
      - api_network
    ports:
      - $PORT:$PORT
    restart: always

  postgres:
    image: clkao/postgres-plv8:12-2
    ports:
      - 5432:5432
    networks:
      - api_network
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
